### ISSUE TITLE
Unable to find RC1 on sonatype

### ISSUE THREAD

**Issue by peeyush-wings** [ifesdjeen/hashed-wheel-timer#2]
Can you please put this on sonatype or maven central so I can use this in my project. Right now I had to work around by commit this alongside my project.

**Comment by colindean** [comment]
I, too, would like to use this in a project. It'd be a lot easier to keep up with releases if it's in maven central or jcenter or something!

**Comment by ifesdjeen** [comment]
It's published on Maven Central, best to my knowledge. I'm going to check right now.

**Comment by colindean** [comment]
Negative: https://search.maven.org/#search%7Cga%7C1%7Chashed-wheel-timer

**Comment by ifesdjeen** [comment]
Right, it was on Sonatype: https://oss.sonatype.org/#nexus-search;quick~hashed-wheel-timer

Although it was "staged". Fixed now. REAMDE updated accordingly.

Thanks for catching it!

**Comment by colindean** [comment]
Thank you so much!
