### ISSUE TITLE
allow scheduling with a 0 millisecond delay?

### ISSUE THREAD

**Issue by kdowney-lot49** [ifesdjeen/hashed-wheel-timer#5]
It's more correct the way you have it: if minimum precision is 10 milliseconds, then a delay of 0 milliseconds is unachievable, and it's not unreasonable to throw an exception. But requiring anyone who wants to schedule "run as soon as possible" to know the timer wheel's resolution also seems wrong; it might be better to round up to the minimum resolution for delays less than the minimum resolution rather than throwing an exception.

**Comment by ifesdjeen** [comment]
Thanks for the suggestions! I think all of them make sense. Unfortunately, I might not get to it immediately, so feel free to send a patch if you like.

**Comment by kdowney-lot49** [comment]
Hi Alex, no worries, I will send you a pull request sometime later this week.

**Comment by kdowney-lot49** [comment]
Note on this fix: I changed just cases with *firstDelay* below the resolution -- it still applies for scheduleFixedRate() and scheduleFixedDelay().
