### ISSUE TITLE
add pluggable nanosecond timer

### ISSUE THREAD

**Issue by kdowney-lot49** [ifesdjeen/hashed-wheel-timer#7]
Allow use of a native RDTSC call in place of System.nanoTime().

**Comment by ifesdjeen** [comment]
I think using a hashed wheel timer defines a native RDTSC timer. The latter suggests precision, while former deliberately trades precision for performance. So far `nanoTime` wasn't known to cause any performance trouble (unlike `getCurrentMillis`), but I'm willing to revise that thought if anyone has a good benchmark.

**Comment by kdowney-lot49** [comment]
I wrote an article on this: based on these findings I think you are right to close the issue.

http://www.cloudwall.io/hashed-wheel-timers
